"""Self-contained research viewer, with explicit matched-period scope."""
import json
from pathlib import Path


def write_report(payload: dict,path: Path) -> None:
    data=json.dumps(payload,ensure_ascii=False).replace('<','\\u003c')
    page='''<!doctype html><html lang="vi"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>La bàn giá + RRG</title>
<style>body{background:#0b1220;color:#e0e9f5;font:14px system-ui;margin:0;padding:20px}main{max-width:1360px;margin:auto}h1{font-size:24px}h2{font-size:18px;margin-top:26px}p{color:#aebfd5;line-height:1.6}.notice{background:#302519;border:1px solid #906b35;border-radius:7px;padding:14px}.cards{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:8px}.card{border:1px solid #334155;border-top:3px solid #47b7e9;border-radius:6px;background:#111c2c;padding:10px}.card b{display:block;margin-bottom:9px}.asset{margin:8px 0}.asset span{display:block;font-size:12px;color:#aebfd5}select{background:#17243b;border:1px solid #526884;color:white;padding:8px;margin:4px}a{color:#6dcfff}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px}td,th{text-align:left;padding:9px;border-bottom:1px solid #28374b;white-space:nowrap}th{color:#9db5d3}summary{cursor:pointer;padding:14px 0}svg{width:100%;background:#0b1424;border:1px solid #334155;border-radius:6px;margin-top:12px}#range{width:40%;vertical-align:middle}#scope{color:#ffcb7c}@media(max-width:850px){.cards{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:500px){body{padding:10px}.cards{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
<main><h1>La bàn D1: trạng thái giá + RRG</h1><p class="notice">Thử nghiệm hồi cứu, chưa chứng minh độ chính xác 75%. Mọi phương án được giữ nguyên sau khi chạy; chưa triển khai làm bộ lọc giao dịch. Ngày xem lại chỉ đổi biểu đồ; bảng hiệu quả luôn tính toàn kỳ kiểm thử ghi bên dưới.</p>
<label>Mô hình biểu đồ <select id="model"><option value="hybrid_logistic">Giá + RRG / logistic</option><option value="hybrid_tree2">Giá + RRG / cây nông</option><option value="price_logistic">Chỉ giá / logistic</option><option value="price_tree2">Chỉ giá / cây nông</option></select></label>
<label>Ngày <input id="range" type="range" min="0" value="0"><span id="asof"></span></label><div class="cards" id="cards"></div>
<svg id="compass" viewBox="0 0 1200 580" aria-label="La bàn xác suất thử nghiệm"></svg>
<p>X = 100 + 100 × (P tăng − 0,5); Y = 100 + 100 × thay đổi P qua 5 quan sát có RRG. Đuôi 12 quan sát, không nối qua lần học lại đầu năm. Mũi tên là dịch chuyển đã xảy ra, không dự báo đường giá. Leading không tự động là Long; cần vượt ngưỡng 75%. Crypto chỉ có quan sát RRG theo lịch nguồn, không đủ bảy ngày/tuần.</p>
<h2>Hiệu quả trên cùng ngày có đủ bốn dự báo ML</h2><label>Mã <select id="symbol"></select></label><label>Chân trời <select id="horizon"><option>5</option><option selected>10</option><option>20</option></select> nến</label><p id="scope"></p>
<div class="scroll"><table><thead><tr><th>Phương án</th><th>Đúng / tín hiệu</th><th>Đúng</th><th>Độ phủ</th><th>Sai</th><th>CI95%</th><th>Mẫu lịch cố định</th><th>Bằng chứng 75%</th></tr></thead><tbody id="metrics"></tbody></table></div>
<p>Tín hiệu tính tại close T, kết quả từ open T+1 đến close T+h. Không TP/SL. Tín hiệu các ngày liên tiếp có kết quả chồng lấn. Ngưỡng xác suất 75% không phải tỷ lệ đúng được bảo đảm. “Hướng mỗi ngày” là chẩn đoán P trên/dưới 50%, không phải ngưỡng thay thế được chọn sau khi xem test.</p>
<details><summary>Long/Short riêng và kiểm tra xác suất — 10 nến</summary><div class="scroll"><table><thead><tr><th>Phương án</th><th>Hướng</th><th>Đúng / tín hiệu</th><th>Đúng</th><th>Độ phủ</th></tr></thead><tbody id="sides"></tbody></table><table><thead><tr><th>Mô hình</th><th>Khoảng P tăng</th><th>Ngày</th><th>P trung bình</th><th>Thực tế tăng</th></tr></thead><tbody id="bins"></tbody></table></div></details>
<details><summary>So sánh cùng ngày cả hai phát hướng — 10 nến</summary><div class="scroll"><table><thead><tr><th>A</th><th>B</th><th>Ngày chung</th><th>A đúng</th><th>B đúng</th><th>Chênh lệch A−B</th><th>CI chênh lệch</th></tr></thead><tbody id="pairs"></tbody></table></div><p>So sánh thăm dò, chưa điều chỉnh cho nhiều phép thử. CI chứa 0 chưa cho thấy khác biệt rõ.</p></details>
<details><summary>Quy tắc cố định trên toàn kỳ 2024+ và kết quả từng năm</summary><p>Phần quy tắc toàn kỳ có cả năm không đủ dữ liệu học ML. Không so trực tiếp tỷ lệ toàn kỳ này với ML ở kỳ ngắn hơn.</p><div class="scroll"><table><thead><tr><th>Quy tắc</th><th>Nến</th><th>Đúng / tín hiệu</th><th>Đúng</th><th>Độ phủ</th></tr></thead><tbody id="rules"></tbody></table><table><thead><tr><th>Năm</th><th>Phương án</th><th>Ngày đủ kết quả</th><th>Đúng / tín hiệu</th><th>Đúng</th><th>Độ phủ</th></tr></thead><tbody id="years"></tbody></table></div></details>
<details><summary>Ranh giới huấn luyện, ổn định và dữ liệu</summary><div class="scroll"><table><thead><tr><th>Năm</th><th>Train</th><th>Calibration</th><th>Trạng thái</th></tr></thead><tbody id="folds"></tbody></table><table><thead><tr><th>Phương án</th><th>Đổi trạng thái</th><th>Đảo trong 5 quan sát</th><th>Ngày giá khớp: đúng / tín hiệu</th><th>Đúng</th></tr></thead><tbody id="stability"></tbody></table></div><p>Khác feed/phiên giữa OHLC và RRG. Ngày giá khớp loại lệch >1%; không đổi kết quả chính. SPY vẫn dùng benchmark SPY nên RRG không có thông tin; không tự đổi benchmark. Ít đổi trạng thái do luôn WAIT/Long không chứng minh hướng ổn định.</p><p id="errors"></p></details>
<p><a href="results.json">Kết quả và hash</a> · <a href="protocol.json">Protocol cố định</a> · <a href="../rrg-comparison-d1/index.html">Đối chiếu RRG trước đó</a> · <a href="../compass-exact-d1/index.html">Compass vòng trước</a></p></main>
<script>const D=__DATA__,$=id=>document.getElementById(id),pct=v=>v==null?'—':(100*v).toFixed(1)+'%',ci=v=>v?v.map(pct).join(' → '):'Chưa đủ mẫu',names=D.models;const dates=[...new Set(Object.values(D.assets).flatMap(a=>a.history.map(r=>r.date)))].sort();$('range').max=Math.max(0,dates.length-1);$('range').value=$('range').max;for(const s of Object.keys(D.assets))$('symbol').add(new Option(s,s));$('symbol').value=D.assets.US500?'US500':Object.keys(D.assets)[0];
function row(id,values){const tr=document.createElement('tr');for(const v of values){const td=document.createElement('td');td.textContent=v??'—';tr.append(td)}$(id).append(tr)}
function draw(){const asof=dates[Number($('range').value)],model=$('model').value; $('asof').textContent=asof||'—';$('cards').replaceChildren();const paths=[];
for(const[group,symbols]of D.groups){const c=document.createElement('div');c.className='card';const title=document.createElement('b');title.textContent=group;c.append(title);for(const s of symbols){const history=(D.assets[s]?.history||[]).filter(r=>r.date<=asof),last=history.at(-1),p=last?.forecasts[model]?.p_up,stale=last&&(Date.parse(asof)-Date.parse(last.date))/86400000>5;const el=document.createElement('div');el.className='asset';el.textContent=s;const label=document.createElement('span');label.textContent=p==null?'Chưa đủ dữ liệu':stale?'Dữ liệu cũ':pct(p)+' tăng · '+(last.forecasts[model].bias==='WAIT'?'Chưa rõ':last.forecasts[model].bias+' thử nghiệm');el.append(label);c.append(el);let tail=[];for(let i=Math.max(5,history.length-12);i<history.length;i++){const a=history[i],b=history[i-5],pa=a.forecasts[model]?.p_up,pb=b.forecasts[model]?.p_up;if(pa==null||pb==null||a.date.slice(0,4)!==b.date.slice(0,4)){tail=[];continue}tail.push({x:100+100*(pa-.5),y:100+100*(pa-pb)})}if(!stale&&p!=null&&tail.length)paths.push({s,tail})} $('cards').append(c)}
const svg=$('compass');svg.replaceChildren();const L=70,R=1130,T=40,B=510,CX=600,CY=275,xmax=Math.max(10,...paths.flatMap(a=>a.tail.map(p=>Math.abs(p.x-100)*1.2))),ymax=Math.max(3,...paths.flatMap(a=>a.tail.map(p=>Math.abs(p.y-100)*1.3))),xx=v=>CX+(v-100)/xmax*530,yy=v=>CY-(v-100)/ymax*235;
function shape(t,attrs,parent=svg){const e=document.createElementNS('http://www.w3.org/2000/svg',t);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);parent.append(e);return e}function text(t,attrs){shape('text',attrs).textContent=t}
for(const[x,y,w,h,color]of [[L,T,530,235,'#122b43'],[CX,T,530,235,'#103326'],[L,CY,530,235,'#311a28'],[CX,CY,530,235,'#35291d']])shape('rect',{x,y,width:w,height:h,fill:color});for(let i=-2;i<=2;i++){const x=CX+i*265,y=CY+i*117.5;shape('line',{x1:x,x2:x,y1:T,y2:B,stroke:i===0?'#adb8c5':'#304157'});shape('line',{x1:L,x2:R,y1:y,y2:y,stroke:i===0?'#adb8c5':'#304157'});text((100+i*xmax/2).toFixed(1),{x,y:535,fill:'#93a8c1','text-anchor':'middle','font-size':12});text((100-i*ymax/2).toFixed(1),{x:60,y:y+4,fill:'#93a8c1','text-anchor':'end','font-size':12})}
for(const[t,x,y]of [['IMPROVING',85,65],['LEADING',1020,65],['LAGGING',85,490],['WEAKENING',1010,490]])text(t,{x,y,fill:'#d6e1f0','font-size':15});const defs=shape('defs',{});
paths.forEach(({s,tail},i)=>{const colors=['#f5ca62','#47c7ff','#ad92ff','#fca765','#68dba1','#f28db4'],color=colors[i%colors.length],p=tail.at(-1),marker=shape('marker',{id:'arrow'+i,viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:7,markerHeight:7,orient:'auto'},defs);shape('path',{d:'M0 0 L10 5 L0 10 Z',fill:color},marker);shape('polyline',{points:tail.map(p=>xx(p.x)+','+yy(p.y)).join(' '),fill:'none',stroke:color,'stroke-opacity':.5,'stroke-width':2});if(tail.length>1){const q=tail.at(-2);shape('line',{x1:xx(q.x),y1:yy(q.y),x2:xx(p.x),y2:yy(p.y),stroke:color,'stroke-width':3,'marker-end':'url(#arrow'+i+')'})}shape('circle',{cx:xx(p.x),cy:yy(p.y),r:4,fill:color});text(s,{x:xx(p.x)+8,y:yy(p.y)-8+(i%2)*18,fill:color,'font-size':14,'font-weight':700})});
}
function tables(){const a=D.assets[$('symbol').value],h=$('horizon').value;if(!a)return;for(const id of ['metrics','sides','bins','pairs','rules','years','folds','stability'])$(id).replaceChildren();$('scope').textContent='Mẫu chung ML: '+a.matched_dates.first+' → '+a.matched_dates.last+' · '+a.matched_dates.count+' ngày dự báo · benchmark RRG '+a.benchmark+'. Các năm không đủ train/calibration không nằm trong bảng chính.';
for(const[m,name]of Object.entries(names)){const r=a.summaries[m][h].ALL;row('metrics',[name,r.wins+' / '+r.signals,pct(r.accuracy),pct(r.coverage),r.false_signals,ci(r.block_ci95),r.scheduled_signals,r.evidence==='not_demonstrated'?'Chưa chứng minh':'Ứng viên hồi cứu']);for(const side of ['LONG','SHORT']){const q=a.summaries[m]['10'][side];row('sides',[name,side,q.wins+' / '+q.signals,pct(q.accuracy),pct(q.coverage)])}const st=a.stability[m],clean=a.price_clean_sensitivity[m];row('stability',[name,st.state_switches,st.opposite_within_5_bars,clean.wins+' / '+clean.signals,pct(clean.accuracy)])}
for(const[m,d]of Object.entries(a.diagnostics))for(const b of d.bins)row('bins',[names[m],b.range.map(pct).join(' → '),b.count,pct(b.mean_p_up),pct(b.actual_up)]);for(const p of a.paired)row('pairs',[names[p.a],names[p.b],p.shared_signals,pct(p.accuracy_a),pct(p.accuracy_b),pct(p.difference_a_minus_b),ci(p.block_ci95_difference)]);for(const[m,hs]of Object.entries(a.rule_full_period))for(const[h,r]of Object.entries(hs))row('rules',[names[m],h,r.wins+' / '+r.signals,pct(r.accuracy),pct(r.coverage)]);for(const[y,mods]of Object.entries(a.yearly))for(const[m,r]of Object.entries(mods))row('years',[y,names[m],r.eligible,r.wins+' / '+r.signals,pct(r.accuracy),pct(r.coverage)]);for(const[y,f]of Object.entries(a.folds))row('folds',[y,f.train.rows+' ngày · '+f.train.first+' → '+f.train.last,f.calibration.rows+' ngày · '+f.calibration.first+' → '+f.calibration.last,f.status]);$('errors').textContent=Object.entries(D.errors).map(([s,e])=>s+': '+e).join(' · ')}
$('range').oninput=draw;$('model').onchange=draw;$('symbol').onchange=tables;$('horizon').onchange=tables;draw();tables();</script></html>'''
    path.write_text(page.replace('__DATA__',data),encoding='utf-8')
