from __future__ import annotations

from .universe import UniverseSymbol


EXNESS_COMMODITIES = {
    "UKOIL",
    "USOIL",
    "XAGUSD",
    "XALUSD",
    "XAUUSD",
    "XCUUSD",
    "XNGUSD",
    "XNIUSD",
    "XPBUSD",
    "XPDUSD",
    "XPTUSD",
    "XZNUSD",
}

EXNESS_FOREX = {
    "AUDCAD",
    "AUDCHF",
    "AUDDKK",
    "AUDHUF",
    "AUDJPY",
    "AUDMXN",
    "AUDNZD",
    "AUDPLN",
    "AUDSEK",
    "AUDSGD",
    "AUDUSD",
    "AUDZAR",
    "CADCHF",
    "CADJPY",
    "CADMXN",
    "CADNOK",
    "CADPLN",
    "CHFDKK",
    "CHFHUF",
    "CHFJPY",
    "CHFMXN",
    "CHFNOK",
    "CHFPLN",
    "CHFSEK",
    "CHFSGD",
    "CHFZAR",
    "EURAUD",
    "EURCAD",
    "EURCHF",
    "EURDKK",
    "EURGBP",
    "EURHKD",
    "EURHUF",
    "EURJPY",
    "EURMXN",
    "EURNOK",
    "EURNZD",
    "EURPLN",
    "EURSEK",
    "EURSGD",
    "EURTRY",
    "EURUSD",
    "EURZAR",
    "GBPAUD",
    "GBPCAD",
    "GBPCHF",
    "GBPDKK",
    "GBPHUF",
    "GBPJPY",
    "GBPMXN",
    "GBPNOK",
    "GBPNZD",
    "GBPPLN",
    "GBPSEK",
    "GBPSGD",
    "GBPUSD",
    "GBPZAR",
    "NZDCAD",
    "NZDCHF",
    "NZDJPY",
    "NZDMXN",
    "NZDPLN",
    "NZDSEK",
    "NZDSGD",
    "NZDUSD",
    "NZDZAR",
    "USDCAD",
    "USDCHF",
    "USDCNH",
    "USDDKK",
    "USDHKD",
    "USDHUF",
    "USDJPY",
    "USDMXN",
    "USDNOK",
    "USDPLN",
    "USDSEK",
    "USDSGD",
    "USDTHB",
    "USDTRY",
    "USDZAR",
}

EXNESS_US_STOCKS = {
    "AAPL",
    "ABBV",
    "ABT",
    "ADBE",
    "ADP",
    "AMD",
    "AMGN",
    "AMT",
    "AMZN",
    "AVGO",
    "AXP",
    "BA",
    "BABA",
    "BAC",
    "BIDU",
    "BIIB",
    "BILI",
    "BMY",
    "C",
    "CHTR",
    "CMCSA",
    "CME",
    "COST",
    "CSCO",
    "CVS",
    "DIS",
    "EA",
    "EBAY",
    "EQIX",
    "F",
    "FDX",
    "FTNT",
    "GILD",
    "GOOG",
    "GOOGL",
    "HD",
    "IBM",
    "INTC",
    "INTU",
    "ISRG",
    "JNJ",
    "JPM",
    "KO",
    "LIN",
    "LLY",
    "LMT",
    "MA",
    "MCD",
    "MDLZ",
    "META",
    "MMM",
    "MO",
    "MRK",
    "MS",
    "MSFT",
    "NFLX",
    "NKE",
    "NTES",
    "NVDA",
    "ORCL",
    "PEP",
    "PFE",
    "PG",
    "PM",
    "PYPL",
    "REGN",
    "SBUX",
    "T",
    "TMO",
    "TMUS",
    "TSLA",
    "UNH",
    "V",
    "VRTX",
    "VZ",
    "WFC",
    "WMT",
    "XOM",
    "ZTO",
}


def filter_exness_supported(items: list[UniverseSymbol]) -> list[UniverseSymbol]:
    return [item for item in items if _is_supported(item)]


def is_exness_supported(item: UniverseSymbol) -> bool:
    return _is_supported(item)


def is_exness_supported_symbol(symbol: str, market: str) -> bool:
    return _is_supported_symbol(symbol, market)


def _is_supported(item: UniverseSymbol) -> bool:
    return _is_supported_symbol(item.symbol, item.market)


def _is_supported_symbol(symbol: str, market: str) -> bool:
    if market == "US stock":
        return symbol in EXNESS_US_STOCKS
    if market == "Forex":
        return symbol in EXNESS_FOREX
    if market in {"Commodity", "Commodity ETF"}:
        return symbol in EXNESS_COMMODITIES
    return True
